spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:${random.uuid}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
releaser:
  git:
    org-name: spring-cloud
    release-train-bom-url: https://github.com/reactor/reactor
    fetch-versions-from-git: true
  meta-release:
    release-train-project-name: reactor
    release-train-dependency-names:
      - reactor
    git-org-url: https://github.com/reactor
cf:
  organization: FrameworksAndRuntimes
  space: Reactor
  reactorAppName: projectreactor
  apiHost: api.run.pivotal.io